# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: guac

env:
  - CGO_ENABLED=0
  - PKG=github.com/guacsec/guac/pkg/version
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/guaccollect
    id: guaccollect
    binary: guaccollect
    ldflags:
      - -X {{.Env.PKG}}.Commit={{.FullCommit}}
      - -X {{.Env.PKG}}.Date={{.Date}}
      - -X {{.Env.PKG}}.Version={{.Summary}}
    goos:
      - linux
      - darwin
      - windows
  - main: ./cmd/guaccsub
    id: guaccsub
    binary: guaccsub
    ldflags:
      - -X {{.Env.PKG}}.Commit={{.FullCommit}}
      - -X {{.Env.PKG}}.Date={{.Date}}
      - -X {{.Env.PKG}}.Version={{.Summary}}
    goos:
      - linux
      - darwin
      - windows
  - main: ./cmd/guacgql
    id: guacgql
    binary: guacgql
    ldflags:
      - -X {{.Env.PKG}}.Commit={{.FullCommit}}
      - -X {{.Env.PKG}}.Date={{.Date}}
      - -X {{.Env.PKG}}.Version={{.Summary}}
    goos:
      - linux
      - darwin
      - windows
  - main: ./cmd/guacingest
    id: guacingest
    binary: guacingest
    ldflags:
      - -X {{.Env.PKG}}.Commit={{.FullCommit}}
      - -X {{.Env.PKG}}.Date={{.Date}}
      - -X {{.Env.PKG}}.Version={{.Summary}}
    goos:
      - linux
      - darwin
      - windows
  - main: ./cmd/guacone
    id: guacone
    binary: guacone
    ldflags:
      - -X {{.Env.PKG}}.Commit={{.FullCommit}}
      - -X {{.Env.PKG}}.Date={{.Date}}
      - -X {{.Env.PKG}}.Version={{.Summary}}
    goos:
      - linux
      - darwin
      - windows

signs:
  -
    # ID of the sign config, must be unique.
    #
    # Default: 'default'
    id: foo
    # Cosign Keyless
  - id: guac-keyless
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}-keyless.sig", "--output-certificate", "${artifact}-keyless.pem", "${artifact}"]
    # artifacts: binary
    artifacts: all
    output: true
  # - id: checksum-keyless
  #   signature: "${artifact}-keyless.sig"
  #   certificate: "${artifact}-keyless.pem"
  #   cmd: cosign
  #   args: ["sign-blob", "--output-signature", "${artifact}-keyless.sig", "--output-certificate", "${artifact}-keyless.pem", "${artifact}"]
  #   artifacts: checksum

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  # name_template: 'checksums.txt'
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
  # name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  skip_upload: false