#
# Copyright 2022 The GUAC Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: release-guac-image

on:
  workflow_dispatch: # testing only, trigger manually to test it works
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  actions: read   # for detecting the Github Actions environment.
  packages: write # To publish container images to GHCR
  id-token: write # needed for signing the images with GitHub OIDC Token

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: ghcr.io/${{ github.repository }}
      IMAGE_URI_TAG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    outputs:
      image: ${{ env.IMAGE_URI }}
      digest: ${{ steps.image_digest.outputs.IMAGE_DIGEST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # tag=v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup pack 
        uses: buildpacks/github-actions/setup-pack@2c2fe0dad1a532cdcde622787d752df8fc3172f0 # v5.1.0
      - name: Build and publish image
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          VERSION=$(git describe --tags --always)
          COMMIT=$(git rev-parse HEAD)
          BUILD=$(date +%FT%T%z)
          PKG=github.com/guacsec/guac/pkg/version
          pack build ${IMAGE_URI_TAG} \
            --builder ${BUILDER} \
            --buildpack ${BUILDPACK} \
            --env BP_GO_BUILD_LDFLAGS="-X ${PKG}.Version=${VERSION} -X ${PKG}.Commit=${COMMIT} -X ${PKG}.Date=${BUILD}" \
            --env BP_GO_TARGETS=${BP_GO_TARGETS}
        shell: bash
        env:
          BP_GO_TARGETS: "./cmd/guaccollect:./cmd/guacone:./cmd/guacingest:./cmd/guacgql:./cmd/guaccsub"
          BUILDER: paketobuildpacks/builder:base
          BUILDPACK: paketo-buildpacks/go
      - name: Push image
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push ${IMAGE_URI}:${{ github.ref_name }}
      - name: Install crane
        if: startsWith(github.ref, 'refs/tags/')
        uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3
      - name: Output image digest
        if: startsWith(github.ref, 'refs/tags/')
        id: image_digest
        run: echo "IMAGE_DIGEST=$(crane digest ${IMAGE_URI_TAG})" >> $GITHUB_OUTPUT

  sign:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/reusable-sign-image-sbom.yaml
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  provenance:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.5.0
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  verify:
    needs: [build, sign, provenance]
    if: startsWith(github.ref, 'refs/tags/')
    # uses: guacsec/guac/.github/workflows/reusable-verify-image.yaml@{ref}
    uses: ./.github/workflows/reusable-verify-image.yaml
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
